#ifndef MEMORY_H_
#define MEMORY_H_
#ifdef __cplusplus
extern "C" {
#endif

#define SRAM_BASE (0x20000000)
#define SRAM_SIZE (144 * 1024)
#define SRAM_END (SRAM_BASE + SRAM_SIZE)

#define FLASH_BASE (0x08000000)
#define FLASH_SIZE = (256 * 1024)
#define FLASH_END (FLASH_BASE + FLASH_SIZE)

#define HEADER_SIZE (256)

#define BOOTLOADER_BASE FLASH_BASE
#define BOOTLOADER_SIZE (56 * 1024)
#define BOOTLOADER_END (BOOTLOADER_BASE + BOOTLOADER_SIZE)
#define BOOTLOADER_HEADER (BOOTLOADER_END - HEADER_SIZE)

#define BANK_SIZE (100 * 1024)

#define BANK1_BASE (BOOTLOADER_BASE + BOOTLOADER_SIZE)
#define BANK1_END (BANK1_BASE + BANK_SIZE)
#define BANK1_HEADER (BANK1_END - HEADER_SIZE)

#define BANK2_BASE (BANK1_BASE + BANK_SIZE)
#define BANK2_END (BANK2_BASE + BANK_SIZE)
#define BANK2_HEADER (BANK2_END - HEADER_SIZE)

#ifdef __cplusplus
}
#endif
#endif // MEMORY_H_
