name: examples

on: push

jobs:
  examples:
    name: ${{ matrix.os }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        compiler:
        - gcc
        - llvm
        generator:
        - default
        include:
          # msvc not supported right now
        # - {os: windows-latest, compiler: msvc}
        - {os: windows-latest, compiler: gcc, generator: Ninja}
        - {os: windows-latest, compiler: llvm, generator: Ninja}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: setup gcc
      if: matrix.compiler == 'gcc'
      run: |
        echo "CC=gcc" >> $GITHUB_ENV
        echo "CXX=g++" >> $GITHUB_ENV
    - name: setup clang
      if: matrix.compiler == 'llvm'
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
    - name: Set non-default generator
      if: matrix.generator != 'default'
      run: echo "CMAKE_GENERATOR=${{matrix.generator}}" >> $GITHUB_ENV
    - name: Build Targets
      run: make
